### ISSUE TITLE
How to make authenticated and guest api calls

### ISSUE THREAD

**Issue by Silassiai** [manchenkoff/breeze-nuxt#14]
Hi, 

Nice starter kit! I would like to see how i can make authenticated and guest api calls to https://github.com/manchenkoff/breeze-api ?
Do i need to add csrf to that calls? Can i use useSanctumClient() for authenticated calls also? How do i catch errors?

**Comment by manchenkoff** [comment]
Hey @Silassiai, thanks! You can check the documentation of the Nuxt module - [nuxt-auth-sanctum](https://manchenkoff.gitbook.io/nuxt-auth-sanctum/usage/composables/usesanctumclient). Basically, whenever you need to call your API, `useSanctumClient` does all things for you including CSRF regardless of authentication state since your API middleware will handle it.

**Comment by Silassiai** [comment]
@manchenkoff thanks so much, nice and clear documentation! 
I missed the docs [nuxt-auth-sanctum](https://manchenkoff.gitbook.io/nuxt-auth-sanctum) (now i see you added the link in the readme, sorry my bad).
