### ISSUE TITLE
CORS error when register

### ISSUE THREAD

**Issue by projct1** [manchenkoff/breeze-nuxt#30]
Hello!

I cloned this repository, changed `baseUrl: 'http://localhost:85'` (because i use WSL), go to `/register` page, trying to register, but got error:
![image](https://github.com/user-attachments/assets/ebbff919-af4d-49cb-aeda-ebb6d57239e3)

With login all is ok!

**Comment by projct1** [comment]
> Hey @projct1, it looks like you should add `localhost:3000` to your `cors.php` on the Laravel side to allow this origin. Check example in [breeze-api](https://github.com/manchenkoff/breeze-api/blob/main/config/cors.php).

I also cloned breeze-api and didn't change anything =\

**Comment by projct1** [comment]
Login works good... No cors error.

**Comment by projct1** [comment]
I don use sail. Standart Ubuntu 22.04 on WSL in Windows 11.
Here is my default `.env`. Changed only DB settings. All primary settings for cors and sanctum i moved down:
```env
APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:PRrDpJbak04tByMuHWf8UAWkYmPPYZWVOxeiqbOgOtA=
APP_DEBUG=true
APP_TIMEZONE=UTC
APP_URL=http://localhost:85

APP_MAINTENANCE_DRIVER=file
# APP_MAINTENANCE_STORE=database

PHP_CLI_SERVER_WORKERS=4

BCRYPT_ROUNDS=12

LOG_CHANNEL=stack
LOG_STACK=single
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=api
DB_USERNAME=root
DB_PASSWORD=12345

DB_CONNECTION_OLD=mysql
DB_HOST_OLD=127.0.0.1
DB_PORT_OLD=3306
DB_DATABASE_OLD=gdebar
DB_USERNAME_OLD=root
DB_PASSWORD_OLD=12345

SESSION_DRIVER=database
SESSION_LIFETIME=120
SESSION_ENCRYPT=false
SESSION_PATH=/

BROADCAST_CONNECTION=log
FILESYSTEM_DISK=local
QUEUE_CONNECTION=database

CACHE_STORE=database
CACHE_PREFIX=

MEMCACHED_HOST=127.0.0.1

REDIS_CLIENT=phpredis
REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=log
MAIL_HOST=127.0.0.1
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS="hello@example.com"
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

VITE_APP_NAME="${APP_NAME}"

SANCTUM_STATEFUL_DOMAINS=localhost:3000
SESSION_DOMAIN=localhost
FRONTEND_URL=localhost:3000
```
Sanctum is default:
![image](https://github.com/user-attachments/assets/1ad7d126-f179-4cb7-bde0-69bad8bbf501)
And `cors.php` too:
![image](https://github.com/user-attachments/assets/9bcee4b9-ca60-47db-992f-59aa086db467)
My frontend url is `localhost:3000`, and my backend api host is `localhost:85`.

I've been sitting here for three days now and can't figure out what the problem is =/

**Comment by manchenkoff** [comment]
@projct1 if you are using `localhost:3000` then you can remove `FRONTEND_URL` and `SANCTUM_STATEFUL_DOMAINS` from your `.env` file since it already contains this address. `SESSION_DOMAIN` also should not be set to prevent networking issues, especially in WSL mode. Then try to restart the app. Btw, how do you run your API? Is it done with `php artisan serve` or smth else?

This behaviour is quite weird to me tbh, if that doesn't help, pls try to attach request headers of `login` and `register` calls, maybe we will be able to find there something. 

Another thing I would personally do is that you can also try to debug your laravel app on the incoming request to make sure what kind of origin you have in the request and what kind of origin you expect in the config. I assume there might be some interference because of WSL.

**Comment by projct1** [comment]
Sigh, i executed `php artisan optimize` and all works fine... Sry for that confuse and thx for your assistance :D
